### PR TITLE
Add some scripts to check deployed certificates.

### PR DESCRIPTION
**Pull request by conet**
The same scripts can also be used to monitor services at TLS level.

These scripts can produce the data displayed in [this dashboard](https://monitor.apifocal.org/dashboard/db/tls-status?orgId=1) when called by telegraf (this still needs to be setup).

### CODE REVIEW

**Comment by conet** [comment]
While running this script I get this output
```
apifocal.com:443 is valid for 61 days
archiva.apifocal.org:443 is valid for 61 days but subject apifocal.com does not match name archiva.apifocal.org
blog.apifocal.com:443 is valid for 61 days
cdn.apifocal.org:443 is invalid for -6 days
dev.silkmq.org:443 is valid for 61 days
dg01.silkmq.org:61917 is valid for 88 days but subject dg02.silkmq.org does not match name dg01.silkmq.org
docker.apifocal.org:443 is valid for 61 days
docker-tmp.apifocal.org:443 is valid for 61 days
docs.silkmq.com:443 is valid for 61 days
ds1.apifocal.org:636 is valid for 88 days
es2.dev.silkmq.org:443 is valid for 88 days
es2.stage.silkmq.org:443 is valid for 61 days
g01.silkmq.com:61617 is valid for 61 days
g02.silkmq.com:61617 is valid for 61 days
g03.silkmq.com:61617 is valid for 61 days
git.apifocal.org:443 is valid for 82 days
jenkins.apifocal.org:443 is valid for 44 days
kibana.dev.silkmq.org:443 is valid for 88 days
kibana.stage.silkmq.org:443 is valid for 61 days
kopf.es2.dev.silkmq.org:443 is valid for 88 days
kopf.es2.stage.silkmq.org:443 is valid for 61 days
ldap.stage.silkmq.org:636 is valid for 61 days
logs.apifocal.org:443 is valid for 44 days
monitor.apifocal.org:443 is valid for 61 days
mqs.dev.silkmq.org:61919 is valid for 88 days
mqs.silkmq.com:61619 is valid for 88 days
mqs.stage.silkmq.org:61919 is valid for 88 days but subject mqs.dev.silkmq.org does not match name mqs.stage.silkmq.org
rancher.apifocal.org:443 is valid for 56 days
rancher.internal.apifocal.org:443 is valid for 88 days
rancher.stage.apifocal.org:443 is valid for 88 days
redmine.apifocal.org:443 is valid for 88 days
sg01.silkmq.org:61917 is valid for 88 days but subject dg01.silkmq.org does not match name sg01.silkmq.org
sg02.silkmq.org:61917 is valid for 88 days but subject dg01.silkmq.org does not match name sg02.silkmq.org
sg03.silkmq.org:61917 is valid for 88 days but subject dg02.silkmq.org does not match name sg03.silkmq.org
silkmq.com:443 is valid for 61 days
stage.apifocal.com:443 is valid for 61 days but subject stage.silkmq.org does not match name stage.apifocal.com
stage.silkmq.org:443 is valid for 61 days
www.silkmq.com:443 is valid for 76 days
www.silkmq.org:443 is valid for 982 days but subject  www.github.com does not match name www.silkmq.org
```
It seems that dev and staging gateway certificates do not properly reflect the DNS configuration, I'm not sure if this means that the dev and stage MQ services are currently down (it depends is MQ clients perform subject verification).

**Comment by CMoH** [comment]
The dev and staging gateway broker names (`dXX.silkmq.org` and `sXX.silkmq.org`) will soon be replaced with host-based certs, and soon production will have the same fate (`gXX.silkmq.org`)

**Comment by CMoH** [comment]
One comment: do add comments to `.tab` files so they are self-documenting. Otherwise their purpose becomes vague after a while.

**Comment by CMoH** [comment]
LGTM. Merging

**Pull request merged**
